<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

<h1 align="center"><font size="5">Supervised Machine Learning: Regression - Final Assignment</font></h1>


## Instructions:

In this Assignment, you will demonstrate the data regression skills you have learned by completing this course. You are expected to leverage a wide variety of tools, but also this report should focus on present findings, insights, and next steps. You may include some visuals from your code output, but this report is intended as a summary of your findings, not as a code review. 

The grading will center around 5 main points:

1. Does the report include a section describing the data?
2. Does the report include a paragraph detailing the main objective(s) of this analysis? 
3. Does the report include a section with variations of linear regression models and specifies which one is the model that best suits the main objective(s) of this analysis.
4. Does the report include a clear and well-presented section with key findings related to the main objective(s) of the analysis?
5. Does the report highlight possible flaws in the model and a plan of action to revisit this analysis with additional data or different predictive modeling techniques? 




## Import the required libraries


In [2]:
###   IMPORTANT NOTE: THIIS PROJECT IS A JULIA CODE, NOT PYTHON. HOWEVER IT DOES THE SAME THING SO THERE SHOULD BE NO PROBLEM .ipynb files support BOTH the julia and python


#using Pkg
#Pkg.add("CSV") ### remove to install these packages
#Pkg.add("DataFrames")
#Pkg.add("MultivariateStats")
#Pkg.add("MLDataUtils")
#Pkg.add("Statistics")

## Importing the Dataset


Before you begin, you will need to choose a data set that you feel passionate about. You can brainstorm with your peers about great public data sets using the discussion board in this module.


Read your chosen dataset into pandas dataframe:


In [2]:
using GLM # For
using CSV # For
using DataFrames # For
using MLDataUtils # For
using Statistics # For
using MultivariateStats # For Ridge

In [5]:
## create the DataFrame
df = DataFrame(CSV.File("Final_Data.csv"))

# Split the data into training and test sets
train, test = splitobs(shuffleobs(df), at = 0.7) #0.7 train and 0.3 test (with shuffle)

test = dropmissing(test) # Drop rows with missing values in the test set

30×3 DataFrame
 Row │ NO     HAPPINESS_INDEX  RELIGIOUSNESS_INDEX 
     │ Int64  Float64          Float64             
─────┼─────────────────────────────────────────────
   1 │     9             0.81                 1.0
   2 │    68             0.83                 0.42
   3 │    95             0.92                 0.25
   4 │    34             0.78                 0.42
   5 │    65             0.97                 0.61
   6 │    83             0.78                 0.33
   7 │    38             0.94                 0.67
   8 │    75             0.53                 0.39
  ⋮  │   ⋮           ⋮                  ⋮
  24 │    80             0.94                 0.33
  25 │    21             0.92                 0.64
  26 │    14             0.86                 0.83
  27 │    31             0.94                 1.0
  28 │    69             0.78                 0.5
  29 │    22             0.86                 0.83
  30 │     3             0.44                 0.83
                                    15 rows omitted

In [7]:
# Linear Regression model
lr_model = lm(@formula(HAPPINESS_INDEX ~ RELIGIOUSNESS_INDEX), train)

StatsModels.TableRegressionModel{LinearModel{GLM.LmResp{Vector{Float64}}, GLM.DensePredChol{Float64, LinearAlgebra.CholeskyPivoted{Float64, Matrix{Float64}, Vector{Int64}}}}, Matrix{Float64}}

HAPPINESS_INDEX ~ 1 + RELIGIOUSNESS_INDEX

Coefficients:
─────────────────────────────────────────────────────────────────────────────────
                         Coef.  Std. Error      t  Pr(>|t|)  Lower 95%  Upper 95%
─────────────────────────────────────────────────────────────────────────────────
(Intercept)          0.713985    0.0559013  12.77    <1e-19   0.602436   0.825534
RELIGIOUSNESS_INDEX  0.0750616   0.0916899   0.82    0.4158  -0.107903   0.258026
─────────────────────────────────────────────────────────────────────────────────

In [8]:
# Polynomial Regression
train[!, :RELIGIOUSNESS_INDEX_SQ] = train[!, :RELIGIOUSNESS_INDEX].^2   # create the RELIGIOUSNESS_INDEX_SQ column in the train
test[!, :RELIGIOUSNESS_INDEX_SQ] = test[!, :RELIGIOUSNESS_INDEX].^2     # create the RELIGIOUSNESS_INDEX_SQ column in the test too
poly_model = lm(@formula(HAPPINESS_INDEX ~ RELIGIOUSNESS_INDEX + RELIGIOUSNESS_INDEX_SQ), train)

StatsModels.TableRegressionModel{LinearModel{GLM.LmResp{Vector{Float64}}, GLM.DensePredChol{Float64, LinearAlgebra.CholeskyPivoted{Float64, Matrix{Float64}, Vector{Int64}}}}, Matrix{Float64}}

HAPPINESS_INDEX ~ 1 + RELIGIOUSNESS_INDEX + RELIGIOUSNESS_INDEX_SQ

Coefficients:
────────────────────────────────────────────────────────────────────────────────────
                            Coef.  Std. Error      t  Pr(>|t|)  Lower 95%  Upper 95%
────────────────────────────────────────────────────────────────────────────────────
(Intercept)              0.768422    0.122075   6.29    <1e-07   0.524759   1.01209
RELIGIOUSNESS_INDEX     -0.171866    0.500111  -0.34    0.7322  -1.17009    0.826359
RELIGIOUSNESS_INDEX_SQ   0.208952    0.415944   0.50    0.6171  -0.621275   1.03918
────────────────────────────────────────────────────────────────────────────────────

In [9]:
# Ridge Regression
X_train = Matrix{Float64}(train[:, [:RELIGIOUSNESS_INDEX, :RELIGIOUSNESS_INDEX_SQ]])
y_train = Vector{Float64}(train[!, :HAPPINESS_INDEX])
ridge_model = ridge(X_train, y_train, 0.5) # 0.5 is the regularization parameter

3-element Vector{Float64}:
 -0.008339546346219381
  0.07116441304030596
  0.7321521937937668

In [11]:
# Predict on the test set
X_test = Matrix{Float64}(test[:, [:RELIGIOUSNESS_INDEX, :RELIGIOUSNESS_INDEX_SQ]])
y_test = Vector{Float64}(test[!, :HAPPINESS_INDEX])


# Predictions
lr_pred = predict(lr_model, test)

30-element Vector{Union{Missing, Float64}}:
 0.7890465128771376
 0.7455107702408307
 0.7327502939508787
 0.7455107702408307
 0.759772479035483
 0.7387552239696796
 0.7642761765495837
 0.7432589214837803
 0.7267453639320777
 0.772532955325435
 ⋮
 0.7867946641200873
 0.7890465128771376
 0.7387552239696796
 0.7620243277925333
 0.7762860365871855
 0.7890465128771376
 0.7515157002596317
 0.7762860365871855
 0.7762860365871855

In [12]:
poly_pred = predict(poly_model, test)

30-element Vector{Union{Missing, Float64}}:
 0.8055083066889008
 0.733097593308986
 0.7385151861531124
 0.733097593308986
 0.7413349762694565
 0.7344612738898306
 0.7470705401141252
 0.7331760393007953
 0.7452436882959003
 0.761493149148109
 ⋮
 0.7983152114458025
 0.8055083066889008
 0.7344612738898306
 0.7440147010908881
 0.7697204992018838
 0.8055083066889008
 0.7347271845396551
 0.7697204992018838
 0.7697204992018838

In [13]:
X_test = hcat(ones(size(X_test, 1)), X_test) # Turn into matrix for ridge
ridge_pred = X_test * ridge_model

30-element Vector{Float64}:
 0.7949770604878534
 0.15070115411592955
 0.055211069025967535
 0.15070115411592955
 0.3075045769190279
 0.0948760838612228
 0.3680037301848076
 0.1307749234155319
 0.0249176022712725
 0.49261009052934707
 ⋮
 0.7495719334434325
 0.7949770604878534
 0.0948760838612228
 0.3370952165775033
 0.5551065627817605
 0.7949770604878534
 0.2102807086223753
 0.5551065627817605
 0.5551065627817605

In [16]:
# Mean Squared Error (MSE)
lr_mse = mean((lr_pred - y_test).^2)
print("Linear Regression MSE = $lr_mse")

Linear Regression MSE = 0.04663153227376573

In [18]:
poly_mse = mean((poly_pred - y_test).^2)
print("Polynomial Regression MSE = $poly_mse")

Polynomial Regression MSE = 0.046386860826652346

In [19]:
ridge_mse = mean((ridge_pred - y_test).^2)

print("Ridge Regression Metrics: MSE = $ridge_mse")

Ridge Regression Metrics: MSE = 0.25219309317974054

In [20]:
println("\nA smaller MSE means a better fit of the model to the data")

# Find the smallest MSE
min_mse = min(lr_mse, poly_mse, ridge_mse)

# Determine which model has the smallest MSE
if min_mse == lr_mse
    println("The Linear Regression model has the smallest MSE: $lr_mse")
elseif min_mse == poly_mse
    println("The Polynomial Regression model has the smallest MSE: $poly_mse")
else
    println("The Ridge Regression model has the smallest MSE: $ridge_mse")
end


A smaller MSE means a better fit of the model to the data
The Polynomial Regression model has the smallest MSE: 0.046386860826652346


Once you have selected a data set, you will produce the deliverables listed below and submit them to one of your peers for review. Treat this exercise as an opportunity to produce analysis that are ready to highlight your analytical skills for a senior audience, for example, the Chief Data Officer, or the Head of Analytics at your company.
Sections required in your report:

*   Main objective of the analysis that specifies whether your model will be focused on prediction or interpretation.
*   Brief description of the data set you chose and a summary of its attributes.
*   Brief summary of data exploration and actions taken for data cleaning and feature engineering.
*   Summary of training at least three linear regression models which should be variations that cover using a simple  linear regression as a baseline, adding polynomial effects, and using a regularization regression. Preferably, all use the same training and test splits, or the same cross-validation method.
*  A paragraph explaining which of your regressions you recommend as a final model that best fits your needs in terms of accuracy and explainability.
*  Summary Key Findings and Insights, which walks your reader through the main drivers of your model and insights from your data derived from your linear regression model.
*  Suggestions for next steps in analyzing this data, which may include suggesting revisiting this model adding specific data features to achieve a better explanation or a better prediction.


# 1. About the Data


In [24]:
'''Brief Description of the Data Set and Summary of its Attributes:
    The dataset I’m working with is derived from a survey that explores a range of topics including personal beliefs, feelings, and religious views.
    It consists of 26 attributes, each representing a different question from the survey. 
    These questions cover a variety of areas such as commitment and involvement in activities that bring joy, perceptions of others’ happiness, 
    reactions to sudden changes in life, trust in others’ honesty, frequency of laughter, appreciation of beauty, feelings of synchronicity with the world, 
    satisfaction in personal relationships, and various aspects of religious belief and practice.'''

'Brief Description of the Data Set and Summary of its Attributes:\n    The dataset I’m working with is derived from a survey that explores a range of topics including personal beliefs, feelings, and religious views.\n    It consists of 26 attributes, each representing a different question from the survey. \n    These questions cover a variety of areas such as commitment and involvement in activities that bring joy, perceptions of others’ happiness, \n    reactions to sudden changes in life, trust in others’ honesty, frequency of laughter, appreciation of beauty, feelings of synchronicity with the world, \n    satisfaction in personal relationships, and various aspects of religious belief and practice.'

In [28]:
'''Brief summary of data exploration:
    To conduct my analysis, I found a survey data on an online website called StatCrunch. This data source includes the survey responses of one hundred individuals that
    may vary by age, gender, or their beliefs in religion. This diversity allowed me to obtain more unbiased results.
    I analysed this data to gather the information that was needed to calculate statistics or test my hypothesis. The survey included many questions about the participants’
    perspective on themselves and religious beliefs. This allowed me to calculate various statistics that helped me to support or reject my arguments. In order to calculate the happiness index
    and the religiousness index for each individual, i took their answers to the survey questions into calculation and scaled accordingly. After that, i got a result from 0 to 1 indicating their levels of religiousness and happiness.'''

'Brief summary of data exploration:\n    To conduct my analysis, I found a survey data on an online website called StatCrunch. This data source includes the survey responses of one hundred individuals that\n    may vary by age, gender, or their beliefs in religion. This diversity allowed me to obtain more unbiased results.\n    I analysed this data to gather the information that was needed to calculate statistics or test my hypothesis. The survey included many questions about the participants’\n    perspective on themselves and religious beliefs. This allowed me to calculate various statistics that helped me to support or reject my arguments. In order to calculate the happiness index\n    and the religiousness index for each individual, i took their answers to the survey questions into calculation and scaled accordingly. After that, i got a result from 0 to 1 indicating their levels of religiousness and happiness.'

# 2. Objectives


In [ ]:
'''Main Objective of the Analysis:
    The purpose of this study is to examine the potential association between an individual’s religious beliefs and their happiness levels. 
    Specifically, the study aims to determine whether an individual’s religious beliefs and activities, can be correlated with their perceptions about themselves 
    and the world around them. To achieve this, I combined what I have learned from this course with findings from an online source that surveyed 100 individuals 
    about their aspects of religiousness and happiness. '''

# 3. Linear Regression Models


In [44]:
'''I trained three different linear regression models on the same training set, which was split from the original dataset. 
    The models include a simple linear regression, a polynomial regression, and a ridge regression.'''




'I trained three different linear regression models on the same training set, which was split from the original dataset. \n    The models include a simple linear regression, a polynomial regression, and a ridge regression.'

In [45]:
'''Simple Linear Regression: This model uses the RELIGIOUSNESS_INDEX as the predictor variable to predict the HAPPINESS_INDEX. It serves as our baseline model.'''

'Simple Linear Regression: This model uses the RELIGIOUSNESS_INDEX as the predictor variable to predict the HAPPINESS_INDEX. It serves as our baseline model.'

In [46]:
'''Polynomial Regression: This model includes an additional polynomial term (RELIGIOUSNESS_INDEX_SQ) to capture any non-linear relationship between the 
    RELIGIOUSNESS_INDEX and the HAPPINESS_INDEX.'''

'Polynomial Regression: This model includes an additional polynomial term (RELIGIOUSNESS_INDEX_SQ) to capture any non-linear relationship between the \n    RELIGIOUSNESS_INDEX and the HAPPINESS_INDEX.'

In [47]:
'''Ridge Regression: This model is similar to the polynomial regression model but includes a regularization term with a lambda of 0.5 to prevent overfitting.'''

'Ridge Regression: This model is similar to the polynomial regression model but includes a regularization term with a lambda of 0.5 to prevent overfitting.'

In [48]:
'''Recommended Model:
    Both the Polynomial and the Linear Regression models (suprisingly not Ridge) displays a pretty good job while interpreting. They give similar results for MSE (Mean Squared Error) 
    on test set. It is totally yours choice to choose which model to implement, however, implementing a linear regression model could be relatively easier.'''

'Recommended Model:\n    Both the Polynomial and the Linear Regression models (suprisingly not Ridge) displays a pretty good job while interpreting. They give similar results for MSE (Mean Squared Error) \n    on test set. It is totally yours choice to choose which model to implement, however, implementing a linear regression model could be relatively easier.'

# 4. Insights and key findings


In [39]:
'''Key Findings and Insights:
    The coefficients of the models provide insights into the relationship between the RELIGIOUSNESS_INDEX and the HAPPINESS_INDEX. 
    For example, in the simple linear regression model, the coefficient of RELIGIOUSNESS_INDEX indicates how much the HAPPINESS_INDEX changes 
    with a one-unit increase in the RELIGIOUSNESS_INDEX, holding all other predictors constant.

    In the polynomial regression model, the coefficients of RELIGIOUSNESS_INDEX and RELIGIOUSNESS_INDEX_SQ together describe a curve that represents the 
    relationship between the RELIGIOUSNESS_INDEX and the HAPPINESS_INDEX.'''

'Key Findings and Insights:\n    The coefficients of the models provide insights into the relationship between the RELIGIOUSNESS_INDEX and the HAPPINESS_INDEX. \n    For example, in the simple linear regression model, the coefficient of RELIGIOUSNESS_INDEX indicates how much the HAPPINESS_INDEX changes \n    with a one-unit increase in the RELIGIOUSNESS_INDEX, holding all other predictors constant.\n\n    In the polynomial regression model, the coefficients of RELIGIOUSNESS_INDEX and RELIGIOUSNESS_INDEX_SQ together describe a curve that represents the \n    relationship between the RELIGIOUSNESS_INDEX and the HAPPINESS_INDEX.'

# 5. Next Steps


In [38]:
'''Suggestions for Next Steps
    1 - Other types of regression models, such as Lasso or Elastic Net, could be explored. 
    These models also include regularization terms and might provide a better fit to the data.
    
    2 - The lambda value in the ridge regression model could be tuned to find the optimal value that minimizes the MSE.
    
    3 - Different strategies for handling missing values could be explored. 
    For example, instead of dropping rows with missing values like we did in our model, imputation methods could be used to 
    fill in the missing values based on the values of other observations.'''

'Suggestions for Next Steps\n    1 - Other types of regression models, such as Lasso or Elastic Net, could be explored. \n    These models also include regularization terms and might provide a better fit to the data.\n    \n    2 - The lambda value in the ridge regression model could be tuned to find the optimal value that minimizes the MSE.\n    \n    3 - Different strategies for handling missing values could be explored. \n    For example, instead of dropping rows with missing values like we did in our model, imputation methods could be used to \n    fill in the missing values based on the values of other observations.'

## <h3 align="center"> © IBM Corporation 2020. All rights reserved. <h3/>
